### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Helveg** [ddikman/sendgrid-dynamic-templates#1]
Could you provide a minimal example? I'm a bit confused how the tool detects what is template, and what is content? Could you demonstrate with a few very minimal files something like this:

* Create a template with a simple hello world header
* Create 2 emails that use the template
* Update the template
* Show that the 2 emails have been updated with the new template

(PS: I'll be fidgeting with the tool, and if it all works and I can figure it out, then I can also PR this)

**Comment by ddikman** [comment]
Thank you for the issue @Helveg , I'm glad to see someone found this tool and that it wasn't just me stumbling on this issue.

I'll try to clarify the docs and provided example a bit.

**Comment by ddikman** [comment]
@Helveg I've pushed a fix now but if it's still not clear, do reopen this.

Also, I'm happy to assist otherwise as well, you can write any question here if needed.

**Comment by Helveg** [comment]
Ah yes, the guide is clearer now! `<!-- EMAIL CONTENT -->` being replaced was the last missing mental piece of the puzzle to understand how it works :)

**Comment by ddikman** [comment]
Excellent, I'm glad it helped! I'm sure it was a bit hard to understand the link with the dynamic template id as well as that wasn't in the example.

**Comment by Helveg** [comment]
Hi! I just wanted to let you know that I made a [CLI tool](https://github.com/Helveg/sendgrid-template-manager) based on the flow you came up with! It instead lets the user merge their premade Designs (from their Design Library) with the content of an existing template into a new template version. I'd love to hear your feedback. This adaptation of your flow makes it so that you don't need to have any local files, everything is maintained on your SendGrid account.

The steps to make this work:
* Make a Design in the Design Library
  * The Design should contain an empty Text module, this is where your content will be inserted.
* Make a Template in the Dynamic Templates
* Create a version called `__content__` in the Template
* Use  `npx sgtm list` to confirm that your Design and Template are available
* Use `npx sgtm apply "My Design Name" "My Template Name"` (or their IDs)

If you want to try it out, give it a go: `npx sgtm --key=<SGKEY> list` will get you started :) (try also `npx sgtm apply --help`. You can place your SendGrid key in a `.env` file or pass it as the `--key` argument.

**Comment by ddikman** [comment]
@Helveg thanks for getting back about it. That's a really neat improvement!

For our case, I wanted to make sure the design files were in source code as well but I can definitely see myself using your CLI in the future instead.

I haven't got the project/situation to test it in at the moment I'm afraid but on a glimpse it looks both useful and well written.

**Comment by Helveg** [comment]
Thanks, if you ever resume an SG project, feel free to open an issue with feature requests for your specific use case. I do not think it would be hard to include local design files! Cheers
